import { prisma } from "../../lib/db";
import { scopeToAssignedClients } from "../../lib/permissions";
import { buildPaginationParams, formatPaginatedResponse } from "../../lib/utils";
import { NotFoundError } from "../../middleware/errorHandler";
import { AuthUser, TaskStatus, TaskPriority } from "@ca-saas/shared-types";

export class TasksService {
  public static async listTasks(user: AuthUser, query: Record<string, any>) {
    const { page, pageSize, skip } = buildPaginationParams(query);
    const clientId = query.clientId as string;
    const status = query.status as TaskStatus;
    const assignedTo = query.assignedTo as string;

    const clientScope = scopeToAssignedClients(user, {});
    const whereCondition: any = { client: clientScope };

    if (clientId) whereCondition.clientId = clientId;
    if (status) whereCondition.status = status;
    if (assignedTo) whereCondition.assignedTo = assignedTo;

    const [tasks, total] = await Promise.all([
      prisma.task.findMany({
        where: whereCondition,
        include: {
          client: { select: { id: true, name: true } },
          assignedUser: { select: { id: true, name: true } }
        },
        skip,
        take: pageSize,
        orderBy: { dueDate: "asc" }
      }),
      prisma.task.count({ where: whereCondition })
    ]);

    const formatted = tasks.map(t => ({
      id: t.id,
      title: t.title,
      clientId: t.clientId,
      clientName: t.client.name,
      moduleRef: t.moduleRef,
      assignedTo: t.assignedTo,
      assignedToName: t.assignedUser?.name || null,
      dueDate: t.dueDate.toISOString().split("T")[0],
      status: t.status as any,
      priority: t.priority as any,
      autoGenerated: t.autoGenerated,
      createdAt: t.createdAt.toISOString(),
      updatedAt: t.updatedAt.toISOString()
    }));

    return formatPaginatedResponse(formatted, total, page, pageSize);
  }

  public static async createTask(
    title: string,
    clientId: string,
    dueDateStr: string,
    priority: TaskPriority,
    assignedTo: string | undefined,
    user: AuthUser
  ) {
    const clientScope = scopeToAssignedClients(user, { id: clientId });
    const client = await prisma.client.findFirst({ where: clientScope });
    if (!client) throw new NotFoundError("Client not found");

    const task = await prisma.task.create({
      data: {
        title,
        clientId,
        assignedTo: assignedTo || client.assignedStaffId || user.id,
        dueDate: new Date(dueDateStr),
        priority: priority || "MEDIUM",
        status: "TODO"
      }
    });

    await prisma.auditLog.create({
      data: {
        userId: user.id,
        action: "TASK_CREATED",
        entityType: "Task",
        entityId: task.id,
        after: { title, priority, dueDateStr }
      }
    });

    return task;
  }

  public static async updateTaskStatus(id: string, status: TaskStatus, user: AuthUser) {
    const task = await prisma.task.findUnique({ where: { id } });
    if (!task) throw new NotFoundError("Task not found");

    const updated = await prisma.task.update({
      where: { id },
      data: { status }
    });

    await prisma.auditLog.create({
      data: {
        userId: user.id,
        action: "TASK_STATUS_UPDATED",
        entityType: "Task",
        entityId: id,
        before: { status: task.status },
        after: { status }
      }
    });

    return updated;
  }
}
