import EventEmitter from "events";
import { prisma } from "./db";
import { logger } from "./logger";
import { WhatsAppProviderFactory } from "../adapters/WhatsAppProvider";
import { DueDateEngine } from "./due-date-engine";

export type EventType =
  | "CLIENT_CREATED"
  | "DOCUMENT_UPLOADED"
  | "DOCUMENT_CHECKLIST_COMPLETED"
  | "ITR_STATUS_CHANGED"
  | "GST_DUE_SOON"
  | "INVOICE_OVERDUE"
  | "PAYMENT_RECEIVED";

export interface EventPayload {
  clientId: string;
  metadata?: Record<string, any>;
}

class AutomationEventBus extends EventEmitter {
  constructor() {
    super();
    this.registerHandlers();
  }

  private registerHandlers() {
    this.on("CLIENT_CREATED", this.handleClientCreated);
    this.on("DOCUMENT_CHECKLIST_COMPLETED", this.handleDocumentChecklistCompleted);
    this.on("ITR_STATUS_CHANGED", this.handleItrStatusChanged);
    this.on("INVOICE_OVERDUE", this.handleInvoiceOverdue);
  }

  private async handleClientCreated(payload: EventPayload) {
    try {
      const client = await prisma.client.findUnique({ where: { id: payload.clientId } }) as any;
      if (!client) return;

      // Prospective leads do not get active statutory filings or onboarding compliance tasks until converted to active
      if (client.status === "LEAD") {
        logger.info(`⚡ Automation Skipped for LEAD inquiry: ${client.name}`);
        return;
      }

      const workType = client.workType || "ITR";
      logger.info(`⚡ Automation Triggered: CLIENT_CREATED for ${client.name} [Work: ${workType}]`);

      // 1. Auto-generate default ITR filing if workType is ITR, ITR + GST, or Tax Audit
      const shouldCreateItr = ["ITR", "ITR + GST", "Tax Audit"].includes(workType);
      if (shouldCreateItr) {
        const defaultItrDueDate = DueDateEngine.calculateItrDueDate({
          assessmentYear: "AY 2026-27",
          formType: client.entityType === "PVT_LTD" ? "ITR_6" : "ITR_3",
          isAuditRequired: client.entityType === "PVT_LTD" || workType === "Tax Audit"
        });

        const existingItr = await prisma.itrFiling.findFirst({
          where: { clientId: client.id, assessmentYear: "AY 2026-27" }
        });

        if (!existingItr) {
          await prisma.itrFiling.create({
            data: {
              clientId: client.id,
              assessmentYear: "AY 2026-27",
              itrFormType: client.entityType === "PVT_LTD" ? "ITR_6" : "ITR_3",
              dueDate: defaultItrDueDate,
              status: "DOCUMENTS_PENDING",
              assignedStaffId: client.assignedStaffId
            }
          });
        }
      }

      // 2. Auto-generate default GST Return Schedule if workType is GST or ITR + GST
      const shouldCreateGst = ["GST", "ITR + GST"].includes(workType);
      if (shouldCreateGst) {
        const existingGst = await prisma.gstReturn.findFirst({
          where: { clientId: client.id, period: "September 2026" }
        });

        if (!existingGst) {
          await prisma.gstReturn.create({
            data: {
              clientId: client.id,
              returnType: "GSTR3B",
              period: "September 2026",
              filingFrequency: "MONTHLY",
              dueDate: DueDateEngine.calculateGstDueDate({
                returnType: "GSTR3B",
                period: "September 2026",
                frequency: "MONTHLY"
              }),
              status: "PENDING"
            }
          });
        }
      }

      // 3. Auto-create onboarding task customized to workType
      let taskTitle = `Complete Document Checklist for ${client.name}`;
      if (workType === "GST Registration") {
        taskTitle = `Complete GST Registration & Verification for ${client.name}`;
      } else if (workType === "Tax Audit") {
        taskTitle = `Prepare Section 44AB Tax Audit Working Papers for ${client.name}`;
      } else if (workType === "TDS/TCS") {
        taskTitle = `TDS/TCS Quarterly Data Collection & 26AS Reco for ${client.name}`;
      } else if (workType === "ITR + GST") {
        taskTitle = `Onboarding & Compliance Setup (ITR + GST) for ${client.name}`;
      }

      const existingTask = await prisma.task.findFirst({
        where: { clientId: client.id, title: taskTitle }
      });

      if (!existingTask) {
        await prisma.task.create({
          data: {
            title: taskTitle,
            clientId: client.id,
            assignedTo: client.assignedStaffId,
            dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
            status: "TODO",
            priority: "HIGH",
            autoGenerated: true
          }
        });
      }
    } catch (err) {
      logger.error({ err }, "Error executing CLIENT_CREATED automation");
    }
  }

  private async handleDocumentChecklistCompleted(payload: EventPayload) {
    try {
      const client = await prisma.client.findUnique({ where: { id: payload.clientId } });
      if (!client) return;

      logger.info(`⚡ Automation Triggered: DOCUMENT_CHECKLIST_COMPLETED for ${client.name}`);

      // Auto-update pending ITR filing to UNDER_PREPARATION
      const pendingItr = await prisma.itrFiling.findFirst({
        where: { clientId: client.id, status: "DOCUMENTS_PENDING" }
      });

      if (pendingItr) {
        await prisma.itrFiling.update({
          where: { id: pendingItr.id },
          data: { status: "UNDER_PREPARATION" }
        });
      }

      // Send WhatsApp confirmation
      const whatsapp = WhatsAppProviderFactory.getProvider();
      await whatsapp.sendMessage({
        clientId: client.id,
        phone: client.contactPhone,
        message: `Hello ${client.name}, all required documents have been received. We have initiated your compliance preparation!`
      });
    } catch (err) {
      logger.error({ err }, "Error executing DOCUMENT_CHECKLIST_COMPLETED automation");
    }
  }

  private async handleItrStatusChanged(payload: EventPayload) {
    try {
      const client = await prisma.client.findUnique({ where: { id: payload.clientId } });
      if (!client) return;

      const { status, formType } = payload.metadata || {};
      logger.info(`⚡ Automation Triggered: ITR_STATUS_CHANGED to ${status} for ${client.name}`);

      const whatsapp = WhatsAppProviderFactory.getProvider();
      await whatsapp.sendMessage({
        clientId: client.id,
        phone: client.contactPhone,
        message: `Dear ${client.name}, your ${formType || "ITR"} status has been updated to: ${status}.`
      });
    } catch (err) {
      logger.error({ err }, "Error executing ITR_STATUS_CHANGED automation");
    }
  }

  private async handleInvoiceOverdue(payload: EventPayload) {
    try {
      const client = await prisma.client.findUnique({ where: { id: payload.clientId } });
      if (!client) return;

      const { invoiceNo, amount } = payload.metadata || {};
      const whatsapp = WhatsAppProviderFactory.getProvider();
      await whatsapp.sendMessage({
        clientId: client.id,
        phone: client.contactPhone,
        message: `Reminder: Invoice ${invoiceNo} of amount ₹${amount} is overdue. Please settle using your UPI link.`
      });
    } catch (err) {
      logger.error({ err }, "Error executing INVOICE_OVERDUE automation");
    }
  }

  public publish(event: EventType, payload: EventPayload) {
    this.emit(event, payload);
  }
}

export const eventBus = new AutomationEventBus();
